"""Add company details to User model

Revision ID: 25b91020e528
Revises: 9df4f27d15c4
Create Date: 2024-09-12 14:37:06.892890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b91020e528'
down_revision = '9df4f27d15c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('resume', sa.Text(), nullable=False))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_application_created_at')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('applicant_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('salary_min',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('salary_max',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_job_created_at')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('company_address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('company_size')
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_name')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('vat_number')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_created_at', ['created_at'], unique=False)
        batch_op.alter_column('employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('salary_max',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('salary_min',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('applicant_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['applicant_id'], ['id'])
        batch_op.create_index('ix_application_created_at', ['created_at'], unique=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('resume')
        batch_op.drop_column('cover_letter')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
