"""Add skills, desired salary, and preferred company size to Profile model

Revision ID: 9df4f27d15c4
Revises: dff4e121dc4f
Create Date: 2024-09-12 13:44:08.309026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df4f27d15c4'
down_revision = 'dff4e121dc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('desired_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_company_size', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('preferred_company_size')
        batch_op.drop_column('desired_salary')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
