"""Add salary range and company size to Job model

Revision ID: dff4e121dc4f
Revises: 0a0364d5305d
Create Date: 2024-09-12 13:06:23.919976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff4e121dc4f'
down_revision = '0a0364d5305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=20), nullable=True))
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('company_size')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')

    # ### end Alembic commands ###
